//Title: WorkoutPlanBuilder.h
//Author: Jeremy Dixon
//Date: 2/17/2026
//Description: This is part of the project in CMSC 202.

//Do not edit this file

#ifndef WORKOUT_PLAN_BUILDER_H //Header guard
#define WORKOUT_PLAN_BUILDER_H //Header guard

#include "Exercise.h"
#include "WorkoutPlan.h"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

// Global Constants
const int MAX_EXERCISES = 100; // Constant with the max number of exercises possible
const int DAYS_IN_WEEK = 7;    // Constant for 7 day plan

class WorkoutPlanBuilder {
  public:
    // Name - WorkoutPlanBuilder()
    // Desc - Default Constructor - Creates a builder with zero loaded exercises
    // Preconditions - None
    // Postconditions - Internal exercise count is set to 0
    WorkoutPlanBuilder();

    // Name - LoadExercises(const string &filename)
    // Desc - Reads exercise records from a file into a fixed array
    // Preconditions - filename refers to a readable input file
    // Postconditions - m_exerciseCount reflects successfully loaded exercises
    int LoadExercises(const string &filename);

    // Name - BuildWeeklyPlan()
    // Desc - Builds and returns a 7-day plan from loaded exercises
    // Preconditions - At least one exercise has been loaded
    // Postconditions - Returned WorkoutPlan contains assignments for each day
    WorkoutPlan BuildWeeklyPlan() const;

    // Name - DisplayLoadedExercises() const
    // Desc - Prints a numbered list of loaded exercises
    // Preconditions - None
    // Postconditions - Exercises displayed to cout
    void DisplayLoadedExercises() const;

    // Name - BuildWeeklyPlanInteractive()
    // Desc - Lets the user choose an exercise for each of 7 days
    // Preconditions - At least one exercise has been loaded
    // Postconditions - Returns a 7-day WorkoutPlan based on user selections
    WorkoutPlan BuildWeeklyPlanInteractive() const;

    // Name - RunMenu()
    // Desc - Displays a simple menu so the user can build, view, save, or load a
    //        7-day workout plan
    // Preconditions - Exercises should be loaded first (LoadExercises)
    // Postconditions - User may create/update a plan and optionally save/load it
    void RunMenu();

  private:
    // Name - FindExerciseIndex(const Exercise &target) const
    // Desc - Attempts to find an exercise in m_exercises that matches target fields
    // Preconditions - None
    // Postconditions - Returns index if found, otherwise -1
    int FindExerciseIndex(const Exercise &target) const;

    // Name - GetIntInRange(int min, int max) const
    // Desc - Gets an int from user in a certain range, re-prompts on invalid input
    // Preconditions - min <= max
    // Postconditions - Returns validated integer
    int GetIntInRange(int min, int max) const;

    Exercise m_exercises[MAX_EXERCISES]; // Keeps track of all of the exercises
    int m_exerciseCount; // Count of the exercises
};

#endif //Header guard
